# Generated by Django 4.1.4 on 2023-01-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuebook',
            name='is_issued',
            field=models.BooleanField(default=False),
        ),
    ]
